### PR TITLE
suggested on board regulator design

### PR DESCRIPTION
**Pull request by LimeProgramming**
Very similar to your own PCB but with a built-in regulator for people who would want that.

I gave the built in regulator it's own folder so you can decide what you want yourself. I did leave a comment about it on youtube but it's vanished, could be a spam filter or something not liking links in comments. Let me know what you think.

### CODE REVIEW

**Comment by scrapcomputing** [comment]
This is really great! Thanks for sharing!

Regarding the merge:
1. I noticed the footprint for the bottom pins and top pins have the same hole sizes 0.57mm. But some of the commonly available headers have different pin sizes (the ones for the top are 0.50mm and the ones for the bottom 0.60mm). Is this a mistake, or did you manage to get such headers with the same hole diameter? 
2. Do you think we could reorganize the files such that both designs share some of the symbols and footprints, e.g. the ones for the sockets? Something like a "common" directory containing the common files?
3. Also from what I can see you first deleted the kicad directory and the re-uploaded it which will mess up the commit history if I merge it as it is. Do you think you could clean it up in your repo so that the deletion/recreation does not show up in the commit history?

Anyway, you did a great job! I will add a link to this in the README, and will also try to figure out what happened to your youtube comment... Thanks again!

**Comment by LimeProgramming** [comment]
hey there.

1. Yeah that was a mistake. I didn't know that the hole sizes were different. I pulled the footprint from your pcb file and I used the one with the most silkscreen to make my own footprints as different files. Easy fix all the same. I did make the pads a little bigger though. 
2. Common folder can be done but would there be a point? Personally I always use project specific library's for symbols and footprints for the sake of making the project easy to share. 
3. Yeah, I'm terrible at dealing with github. What would be the easiest way to "reset" my fork then I can just use the github desktop for managing the files. 

Oh btw, you're missing some files needed by kicad in your repo, I had to remake the top and bottom symbols before the schematic would open properly

**Comment by LimeProgramming** [comment]
What I'll do is close this PR, delete my fork, re-create my fork and upload my changes to another branch. then you can pick and choose what you want to merge into the main branch. that should hopefully work.

**Comment by scrapcomputing** [comment]
1. Good to know :) I deliberately made the pads really small because otherwise it is easier for solder to create a big blob and stick to the nearby header. But anyway, as long as they are not too big it should be fine.
2. Well, if there are no shared files between the projects, then merging them in a single repo will just make them harder to manage. If they share files, then improving e.g. the footprint for one will automatically improve the footprint for the other. But yeah, that can result in extra work in having to maintain them both on every change.
3. The thing is that the pull request won't let you pick and choose files, it is either all or nothing.

Thanks for letting me know. I was sure that something was missing, but kicad is caching all these files and it is hard to know. I added the missing library to the repository.

The best way is to create a new fork, then add your files in a separate directory, so that they can be merged with no conflicts. Btw, I noticed that you created a separate branch and pushed your changes there. This is not ideal, try to stick to the "main" branch.
But I don't think we need to worry too much about merging them for now since they won't be sharing much except for parts of the README, it will most probably make it harder to synchronize and maintain both projects. The important thing is to make people in the community aware of awsome projects like this. So I will add a section in the Readme with links to this and any other similar projects.

**Comment by LimeProgramming** [comment]
Hello

Yeah honestly I thought that it would give the option to merge into another branch on your end and then you could choose what you wanted. Like I said, I'm useless with GitHub, sorry about that. I'm not normally one for pull requests I've just made this for the sake of saying "here, I made some edits" since youtube comments were unreliable. I didn't know how else to let you know this existed. 

I know what you mean about the soldering, honestly for that kind of thing Id be inclined to drown the board in flux and use some leaded solder, Just let it flow. Though I could see in your video it did look like you were struggling to get a solid contact between the pins and pads because they were so small so I took a stab at making the pads a little larger. 

Honestly you can do what ever you like with my edits.
If you want to just link it in the readme, that's cool
If you want to download my fork, take what you want from it (if anything) and then upload that to your own repo. 100% okay.
You tell me what you prefer.

PS, on the note of youtube comments, I did leave a comment on youtube saying that I made a thread on Vogons about this project since I didn't see one on there already from you: https://www.vogons.org/viewtopic.php?f=46&t=92036
Vogons, the retro web discord and dos reloaded are good places to spread the word about this.

Take it easy.

**Comment by scrapcomputing** [comment]
Hi, 

Yeah I could merge the branch, but it is usually best to just keep everything in the main branch for simplicity. I am not sure what happened to your comments, it did not show up in the spam list, sorry about that. But anyway, thanks for reaching out, I am really interested in your design, and I think it would be awesome to have an onboard regulator!.

Haha yes, lots of flux should make it a lot easier to solder. I am not great at soldering, and having a camera in the way is not helping haha :D 

I think it is probably better to keep them separate for now, as there is not too much source code to share across the projects, and that would also remove the need to synchronize which can be painful. I will definitely add a list with links so that all similar projects are visible.

Oh cool, good to know about the vogons thread. I will follow it. Please share your experience with the board once you build it, I would be really interested in it.

Thanks!

**Pull request closed without merging**
